apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: danielrojas1920/django_pia_lm_image:latest  # La imagen Docker de tu app
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql://PIA_LMP:9WG\"\"u4:85M@mysql-service:3306/PIA_LMP"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
  type: LoadBalancer  # O NodePort, dependiendo de tus necesidades
