version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: PIA_LMP
      MYSQL_USER: PIA_LMP
      MYSQL_PASSWORD: 9WG""u4:85M
      MYSQL_ROOT_PASSWORD: 9WG""u4:85M
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
