
version: '3.8'

services:
  web:
    container_name: $DjangoTest_web
    build: .
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8085:8000'
    expose:
      - '8000'
    links:
      - mysql
    networks:
      backend:
        ipv4_address: 192.20.0.5

  mysql:
    container_name: $DjangoTest_db
    image: 'mysql:5.7'
    volumes:
      - './database/data:/var/lib/mysql'
    ports:
      - '3308:3306'
    networks:
      backend:
        ipv4_address: 192.20.0.6
    environment:
      MYSQL_DATABASE: PIA_LMP
      MYSQL_ROOT_PASSWORD: 9WG""u4:85M

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.20.0.0/24
